stages:
  - DeployDev

DeployDev:
  stage: DeployDev
  image: hblabvn/php-mongo:latest
  only:
    - develop
  environment:
    name: dev
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
  script:
    - eval $(ssh-agent -s) && echo "$DEV_DEPLOY_SSH_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\tControlMaster auto\n\tControlPath /tmp/ansible-%r@%h:%p\n\tControlPersist 15m\n\tPreferredAuthentications publickey
  \n\n" > ~/.ssh/config'
    - chmod go-wrx ~/.ssh
    - chmod +x -R .platform/hooks
    - composer global require hirak/prestissimo -q
    - composer require --dev knuckleswtf/scribe
    - composer install --ignore-platform-reqs --no-scripts -q && composer dump-autoload -q
    - echo "$DEV_DEPLOY_ENV_FILE" > .env && echo "OK" > public/health.html
    - rsync -azPq --exclude='.git' ./ $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST:$DEV_DEPLOY_DIR/
    - ssh $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST "cd $DEV_DEPLOY_DIR && eb deploy $DEV_EB_ENV_NAME -l $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
