stages:
  - CheckPhpcs
  - CheckSonar
  - DeployDev

.PhpcsScan: &PhpcsScan |
  pushComment(){
      curl --request POST --header "PRIVATE-TOKEN: $USER_TOKEN" \
      --form "note=$OUTPUT" --form "path=dudeism.md" \
      --form "line=1" --form "line_type=new" \
      https://git.hblab.vn/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/comments
      echo $OUTPUT
      exit 1
  }

  OUTPUT=$(phpcs --standard=PSR2 app/) || pushComment

.CheckSonarqube: &CheckSonarqube |
  sonar-scanner -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.user_token=$USER_TOKEN -Dsonar.login=$SONAR_KEY

Phpcs:
  stage: CheckPhpcs
  image: php:7.2-alpine
  script:
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
    - mv phpcs.phar /usr/local/bin/phpcs && chmod +x /usr/local/bin/phpcs
    - mv phpcbf.phar /usr/local/bin/phpcbf && chmod +x /usr/local/bin/phpcbf
    - *PhpcsScan
  except:
    - master


Sonar:
  stage: CheckSonar
  image: hblabvn/sonar-scanner:latest
  only:
    - develop
  script:
    - *CheckSonarqube

DeployDev:
  stage: DeployDev
  image: hblabvn/php-mongo:latest
  only:
    - beta
  environment:
    name: dev
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/
  script:
    - eval $(ssh-agent -s) && echo "$DEV_DEPLOY_SSH_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\tControlMaster auto\n\tControlPath /tmp/ansible-%r@%h:%p\n\tControlPersist 15m\n\tPreferredAuthentications publickey
  \n\n" > ~/.ssh/config'
    - chmod go-wrx ~/.ssh
    - chmod +x -R .platform/hooks
    - composer global require hirak/prestissimo -q
    - composer require --dev knuckleswtf/scribe
    - composer install --ignore-platform-reqs --no-scripts -q && composer dump-autoload -q
    - echo "$DEV_DEPLOY_ENV_FILE" > .env && echo "OK" > public/health.html
    - rsync -azPq --exclude='.git' ./ $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST:$DEV_DEPLOY_DIR/
    - ssh $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST "cd $DEV_DEPLOY_DIR && eb deploy $DEV_EB_ENV_NAME -l $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
